Numpy_Assignment

In [1]:
import numpy as np

In [3]:
arr=np.array([1,7,13,105])
print(arr)
print(f"size of element of array= {arr.itemsize}")
print(f"no of elements present in array = {arr.size}")
print("so total size of array = element size * no of elements")
print(f"size of arr in bytes ={arr.nbytes}")

[  1   7  13 105]
size of element of array= 8
no of elements present in array = 4
so total size of array = element size * no of elements
size of arr in bytes =32


In [6]:
arr1=np.array([10,20,30,40,50])
arr2=np.array([30,20,10,50,10])
for i in range(0,5):
    if(arr1[i]>arr2[i]):
        print(f"{arr1[i]} is greater than {arr2[i]}")
    elif(arr1[i]<arr2[i]):
        print(f"{arr1[i]} is less than {arr2[i]}")
    elif(arr1[i]>=arr2[i] or arr1[i]==arr2[i]):
        print(f"{arr1[i]} is greater qual {arr2[i]}")
    elif(arr1[i]<=arr2[i] or arr1[i]==arr2[i]):
        print(f"{arr1[i]} is less equal {arr2[i]}")    

10 is less than 30
20 is greater qual 20
30 is greater than 10
40 is less than 50
50 is greater than 10


In [29]:
tenz=np.zeros(10)
print(f"array of 10 zeros = {tenz}")
teno=np.ones(10)
print(f"array of 10 ones = {teno}")
ten5=np.ones(10)*5
print(f"array of 10 fives = {ten5}")
ten10=np.ones(10)*10
print(f"array of 10 tens = {ten10}")
ten20=np.ones(10)*20
print(f"array of 10 twenty = {ten20}")
ten50=np.ones(10)*50
print(f"array of 10 fifty = {ten50}")

arr_all= np.concatenate((tenz,teno,ten5,ten10,ten20,ten50))
print(f"array concatenation=")
print(arr_all)
print(f"Dtype = {tenz.dtype}")

array of 10 zeros = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
array of 10 ones = [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
array of 10 fives = [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
array of 10 tens = [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
array of 10 twenty = [20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]
array of 10 fifty = [50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]
array concatenation=
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5. 10. 10. 10. 10. 10. 10.
 10. 10. 10. 10. 20. 20. 20. 20. 20. 20. 20. 20. 20. 20. 50. 50. 50. 50.
 50. 50. 50. 50. 50. 50.]
Dtype = float64


In [31]:
arr_range_30_70=np.arange(30,71)
print(arr_range_30_70)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]


In [36]:
arr_range_50_95=np.arange(50,96)
print(arr_range_50_95)

[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [45]:
arr_odd_20_80=np.arange(21,80,2)
print(arr_odd_20_80)

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [48]:
rand15 = np.random.randint(10,40,15)
print(rand15)

[13 16 35 23 36 12 12 39 28 25 28 30 27 32 33]


In [50]:
rand10 = np.random.randint(30,50,10)
print(rand10)

[41 48 45 34 42 32 46 38 49 33]


In [51]:
rand20 = np.random.randint(50,90,20)
print(rand20)

[59 80 76 80 73 86 65 57 73 61 73 88 63 54 83 73 80 65 70 75]


In [68]:
arr1=np.arange(10,20,2)
arr2=np.arange(30,40,2)
print(f"array1 = {arr1}")
print(f"array2 = {arr2}")
print(f"array additon {arr1+arr2}")
print(f"array multiplication {arr1*arr2}")
print(f"array substraction {arr1-arr2}")
print(f"array division {arr1/arr2}")

array1 = [10 12 14 16 18]
array2 = [30 32 34 36 38]
array additon [40 44 48 52 56]
array multiplication [300 384 476 576 684]
array substraction [-20 -20 -20 -20 -20]
array division [0.33333333 0.375      0.41176471 0.44444444 0.47368421]


In [70]:
arr3=np.arange(10,22)
print(f"array of 10 to 21 {arr3}")
arr4=arr3.reshape([3,4])
print(f"array of 10 to 21 in 3 row 4 col ")
print(arr4)

array of 10 to 21 [10 11 12 13 14 15 16 17 18 19 20 21]
array of 10 to 21 in 3 row 4 col 
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [2]:
arr5=np.zeros(9)
print(arr5)
c=0
for i in range (1,4):
    for j in range(1,4):
        print(f"i={i} j= {j}")
        if i==j:
            arr5[c]=1
        c=c+1

print(arr5)
arr6=arr5.reshape([3,3])
print(arr6)

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
i=1 j= 1
i=1 j= 2
i=1 j= 3
i=2 j= 1
i=2 j= 2
i=2 j= 3
i=3 j= 1
i=3 j= 2
i=3 j= 3
[1. 0. 0. 0. 1. 0. 0. 0. 1.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [3]:
# 13 using identity matrix

In [4]:


# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print("3x3 Identity Matrix:")
print(identity_matrix)


3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
print(arr6.ndim)

2


In [7]:
row,col=arr6.shape
print(f"rows= {row} column = {col}")

rows= 3 column = 3


In [9]:

#  15. Write a NumPy program to create a 5x5 zero matrix with elements on the  main diagonal equal to 1, 2, 3, 4, 5.


In [16]:
arr7=np.zeros(25)
#print(arr7)
c=0
n=1
for i in range (1,6):
    for j in range(1,6):
       # print(f"i={i} j= {j}")
        if i==j:
            arr7[c]=n
            n=n+1
        c=c+1
        
#print(arr7)
arr8=arr7.reshape([5,5])
print(arr8)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [21]:
arr9=np.random.randint(1,50,27)
print(arr9)
arr9=arr9.reshape([3,3,3])
print(arr9)

[27  9  4 42 17 44 37 35 46 14 44  3 33 34  5 36 13 19 29 29 49 26 47 30
 38 48 30]
[[[27  9  4]
  [42 17 44]
  [37 35 46]]

 [[14 44  3]
  [33 34  5]
  [36 13 19]]

 [[29 29 49]
  [26 47 30]
  [38 48 30]]]


In [28]:
arr10=np.random.randint(1,50,24)
#print(arr9)
arr10=arr10.reshape([2,3,4])
print(arr10)

[[[ 9  2 25 13]
  [19  9  6 29]
  [31 33 23  3]]

 [[ 3 44 35 19]
  [ 3 13 25 41]
  [ 1 45 36 35]]]


In [29]:
print(arr10.shape)

(2, 3, 4)


In [30]:
l1=[11,22,33,44,55,66,77]

In [32]:
print(f"l1={l1} type of l1={type(l1)}")

l1=[11, 22, 33, 44, 55, 66, 77] type of l1=<class 'list'>


In [33]:
nparr=np.array(l1)

In [34]:
print(f"nparr={l1} type of l1={type(nparr)}")

nparr=[11, 22, 33, 44, 55, 66, 77] type of l1=<class 'numpy.ndarray'>


In [39]:
arr12=np.arange(2,11)
print(arr12)
arr12=arr12.reshape([3,3])
print(arr12)

[ 2  3  4  5  6  7  8  9 10]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [41]:
arr13=np.arange(12,39)
print(arr13)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [51]:
arr13=np.array([10,20,30,40,50,50,77])
arr13=np.flip(arr13)
print(arr13)


[77 50 50 40 30 20 10]


In [54]:
arr14=np.array([10,20,30,40,50,50,77])
arr14=np.flipud(arr14)
print(arr14)


[77 50 50 40 30 20 10]


In [55]:
arr15=np.array([10,20,30,40,50,50,77])
arr15=arr15[::-1]
print(arr15)

[77 50 50 40 30 20 10]


In [56]:
arr17 = np.arange(7)
print(arr17)

print("Element-wise remainder of division:")
print(np.remainder(arr17, 5))


[0 1 2 3 4 5 6]
Element-wise remainder of division:
[0 1 2 3 4 0 1]


In [58]:
arr18=arr17.astype(float)
print(arr18)

[0. 1. 2. 3. 4. 5. 6.]


In [59]:
arr19 = np.arange(20,50)
print(arr19)

print("Element-wise remainder of division:")
print(np.remainder(arr19, 3))

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]
Element-wise remainder of division:
[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
